name: Run INDPE Sunday Midnight

on:
  schedule:
    - cron: "30 18 * * 6"   # Sunday 00:00 IST
  workflow_dispatch:

jobs:
  run-indpe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run INDPE
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NEW: ${{ secrets.NEW2 }}
        run: python indpe.py
